// <auto-generated />
using System;
using Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220427195054_addRequiredAttrInRoleField")]
    partial class addRequiredAttrInRoleField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Data.Entities.casbin_rule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ptype")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("v0")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("v1")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("v2")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("v3")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("v4")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("v5")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("id");

                    b.ToTable("casbin_rule");
                });
#pragma warning restore 612, 618
        }
    }
}
